[target.riscv64gc-unknown-linux-musl]
image = "ghcr.io/cross-rs/riscv64gc-unknown-linux-musl:main"

[target.loongarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-musl:main"

[target.loongarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/loongarch64-unknown-linux-gnu:main"
