name = "poof-pkg"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "poof-packages"

[[routes]]
pattern = "poof-pkgs.fpira.com/*"
zone_name = "fpira.com"
