name: AUR Package Update

on:
  workflow_run:
    # this matches the name of the workflow .github/workflows/release.yml
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aur_generate:
    name: Generate AUR package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup makepkg
        run: |
          sudo apt-get update
          sudo apt-get install -y pacman-package-manager

      - name: Create virtual environment
        working-directory: scripts/aur-packaging
        run: python3 -m venv .venv

      - name: Install dependencies
        working-directory: scripts/aur-packaging
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate PKGBUILD
        working-directory: scripts/aur-packaging
        run: |
          source .venv/bin/activate
          python3 update.py

      - name: Generate .SRCINFO
        working-directory: scripts/aur-packaging
        run: |
          rm -f .SRCINFO
          makepkg --printsrcinfo > .SRCINFO

      - name: List files
        working-directory: scripts/aur-packaging
        run: |
          ls -la

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: poof-bin
          path: |
            scripts/aur-packaging/PKGBUILD
            scripts/aur-packaging/.SRCINFO
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1
          compression-level: 0  # no compression

