name: MacPorts Portfile
run-name: MacPorts Portfile ${{ github.ref_name }}

on:
  release:
    # only for newly published releases, not drafts or updates to existing ones
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to package (e.g. 1.2.3, without v prefix)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  macports-portfile:
    name: Generate and submit Portfile
    runs-on: macos-13
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      GIT_USER_NAME: pirafrank
      GIT_USER_EMAIL: pirafrank@users.noreply.github.com
      SOURCES_CONF: "/opt/local/etc/macports/sources.conf"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MacPorts
        uses: melusina-org/setup-macports@v1

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo2ports
        run: |
          sudo port selfupdate
          sudo port install pipx
          pipx install git+https://github.com/herbygillot/cargo2ports.git

      - name: Configure local ports tree
        run: |
          echo "pwd: $(pwd)"
          echo "home: $HOME"
          LOCAL_PORTS="file:///$HOME/pirafrank/ports [nosync]"
          mkdir -p "$HOME/pirafrank/ports/sysutils/poof"
          sudo bash -c "echo '$LOCAL_PORTS' | cat - '$SOURCES_CONF' > /tmp/sources.conf.tmp && mv /tmp/sources.conf.tmp '$SOURCES_CONF'"
          echo "Prepended '$LOCAL_PORTS' to $SOURCES_CONF"

      - name: Generate Portfile
        run: |
          chmod +x macports/generate_portfile.sh
          ./macports/generate_portfile.sh ${{ steps.version.outputs.version }}

      - name: Add Portfile to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Portfile
          path: "./macports/Portfile"
          if-no-files-found: error
          retention-days: 7
          compression-level: 0  # no compression

      - name: Submit MacPorts PR
        if: false  # Disable PR submission for now, enable when ready
        run: |
          chmod +x macports/macport_pr.sh
          ./macports/macport_pr.sh "$(pwd -P)/macports/Portfile"
